version: '2'
services:
  db:
   build: ./db
   hostname: db
   environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw
     - MYSQL_USER=usuario
     - MYSQL_PASSWORD=user-secret-pw
   ports:
     - 3306:3306
   volumes:
     - db_data:/var/lib/mysql
     - ./code/dump:/docker-entrypoint-initdb.d

  node:
    image: "node:carbon"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./code/app:/home/node/app
    ports:
      - 3000:3000
    depends_on:
     - mongodb
     - db
    command: "npm start"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./code/scripts/mongod.conf:/etc/init/mongod.conf
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=my-admin-pw

  web:
    image: unixelias/lamp:demo
    hostname: web
    ports:
      - 80:80
      - 443:443
    environment:
      - LOG_STDOUT=true
      - LOG_STDERR=true
      - LOG_LEVEL=debug
    volumes:
      - ./code/www:/var/www/html
    depends_on:
     - db
     - node
     - mongodb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    hostname: phpmyadmin
    volumes:
      - phpmyadmin_data:/sessions
    ports:
      - 8090:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=my-secret-pw
    depends_on:
      - db

volumes:
  db_data:
  phpmyadmin_data:
  mongo-data:
