version: '2'
services:
  db:
    image: mysql:latest
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - db_data:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
  web:
    image: unixelias/lamp
    ports:
      - 80:80
    environment:
      - LOG_STDOUT=true
      - LOG_STDERR=true
      - LOG_LEVEL=debug
    volumes:
      - ~/workspace:/var/www/html
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - phpmyadmin_data:/sessions
    ports:
      - 8090:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=my-secret-pw
    depends_on:
      - db

volumes:
  db_data:
  phpmyadmin_data:
