version: '2'
services:
  db:
   image: mariadb
   hostname: db
   environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw
     - MYSQL_USER=usuario
     - MYSQL_PASSWORD=user-secret-pw
   ports:
     - 3306:3306
   volumes:
     - db_data:/var/lib/mysql
     - ./demo/dump:/docker-entrypoint-initdb.d
  web:
    image: unixelias/lamp:16.04
    hostname: web
    ports:
      - 80:80
    environment:
      - LOG_STDOUT=true
      - LOG_STDERR=true
      - LOG_LEVEL=debug
    volumes:
      - ./demo/code:/var/www/html
    depends_on:
     - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    hostname: phpmyadmin
    volumes:
      - phpmyadmin_data:/sessions
    ports:
      - 8090:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=my-secret-pw
    depends_on:
      - db
      - web

volumes:
  db_data:
  phpmyadmin_data:
